// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $index1 from "./routes/index1.tsx";
import * as $ChainSubmit from "./islands/ChainSubmit.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $FileUpload from "./islands/FileUpload.tsx";
import * as $UploadButton from "./islands/UploadButton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/index1.tsx": $index1,
  },
  islands: {
    "./islands/ChainSubmit.tsx": $ChainSubmit,
    "./islands/Counter.tsx": $Counter,
    "./islands/FileUpload.tsx": $FileUpload,
    "./islands/UploadButton.tsx": $UploadButton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
